version: '3.9'

services:
  client:
    build: recipe-app
    image:  kylet1699/recipe-app-client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: recipe-app-server
    image: kylet1699/recipe-app-server
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - DB_URL=mongodb://mongo:27017/recipe-app

  mongo:
    image: mongo
    volumes:
      - .mongo_data:/data/db
    ports:
    - 27017:27017